name: terraform initialization
run-name: terraform install
on:
 workflow_dispatch:
  inputs:
   environments:
    description: 'please select the environments'
    default: dev
    required: true
    type: choice
    options:
     - dev
     - prod
     - staging
    run: echo "${{ github.event.inputs.environments }} 
   
jobs:
 build-job:
  runs-on: ubuntu-latest
  environment: ${{ github.event.inputs.environment }}
  steps:
   - name: checkout
     uses: actions/checkout@v4.2.2  
     with:
        token: ${{ secrets.TOKEN }}
        ref: 'main'
        # fetch-depth: 0
   - name: set hashicorp  
     uses: hashicorp/setup-terraform@v2.0.3
     with:
      terraform-version: 5.48.0
   
   - name: configue git
     run: |
      git config --global user.name 'agarapunaveen'
      git config --global user.email 'agarapunaveen@gmail.com'

   - name: configure AWS credential
     uses: aws-actions/configure-aws-credentials@v4
     with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
      aws-region: us-east-1
   - name: initialize terraform
     run: terraform init
   # - name: install docs
   #   run: sudo snap install terraform-docs
   # - name: select terraform workspaces
   - name: check if workspace exists or not
     run: |
      workspace_new="${{ github.event.inputs.environment == 'dev' || 'dev' &&  github.event.inputs.environment == 'prod' || 'prod' }}" 
      # workspace_new="${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/dev' && 'dev' || 'dev' }}" 
      terraform workspace list | grep -w "$workspace_new" || terraform workspace new "$workspace_new"
     id: create_workspace
     
   - name: Select Terraform Workspace 
     run: | 
      workspace_new="${{ github.event.inputs.environment == 'dev' || 'dev' &&  github.event.inputs.environment == 'prod' || 'prod' }}" 
     
       # workspace_new="${{ github.ref == 'refs/heads/main' && 'prod' || github.ref == 'refs/heads/dev' && 'dev' || 'dev' }}" 
       terraform workspace select "$workspace_new"
     id: select_workspace  
      # terraform workspace show 
      # terraform workspace select ${{ github.event.inputs.environment || 'dev' }} || terraform workspace new ${{ github.event.inputs.environment }}
     # run: |
      # terraform workspace new dev
      # terraform workspace new prod
      # terraform workspace select ${{ github.event.inputs.environment }}
   - name: plan terraform
     run: terraform plan -out=tfplan
     

   - name: Render terraform docs and push changes back to PR
     if: ${{ github.event_name == 'pull_request' }}
     uses: terraform-docs/gh-actions@main
     with:
        working-dir: .
        output-file: README.md
        output-method: inject
        git-push: "true"    

      
   - name: apply terraforms
     if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
     run: terraform apply -auto-approve tfplan
