name: terraform destroy
on:
 workflow_dispatch:
jobs:
 terraform-cleanup:
  runs-on: ubuntu-latest
  steps:
   - name: checkout github repository
     uses: actions/checkout@v2
   - name: configure AWS credentials
     uses: aws-actions/configure-aws-credentials@v4
     with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
      aws-region: us-east-1
   - name: set hashicorp  
     uses: hashicorp/setup-terraform@v2.0.3
     with:
      terraform-version: 5.48.0  
   - name: terraform init
     run: terraform init
   - name: terraform plan to destroy
     run: terraform plan -destroy -out=tfplan-destroy
   - name: terrform apply to destroy
     run: terraform apply -destroy -auto-approve tfplan-destroy
  
 
